title: Mission Société Numérique
description: Stratégie nationale pour un numérique inclusif
author: Mission Société Numérique
twitter:
    username: MissionSoNum
social:
    links:
        - https://twitter.com/MissionSoNum
        - https://github.com/SocieteNumerique
lang: fr_FR

markdown: kramdown

collections:
    livrables:
        output: true


plugins:
    - jekyll-seo-tag
    - jekyll-sitemap
